---
name: "IMGREC"
dataIns:
- name: "s3bucket"
  type: "string"
  source: "s3bucket"
- name: "topic_arn"
  type: "string"
  source: "topic_arn"
- name: "desired_num_splits"
  type: "number"
  source: "desired_num_splits"
- name: "s3prefix"
  type: "string"
  source: "s3prefix"
workflowBody:
- function:
    name: "ir-split"
    type: "String"
    dataIns:
    - name: "s3bucket"
      type: "string"
      source: "IMGREC/s3bucket"
    - name: "desired_num_splits"
      type: "number"
      source: "IMGREC/desired_num_splits"
    - name: "s3prefix"
      type: "string"
      source: "IMGREC/s3prefix"
    dataOuts:
    - name: "batches"
      type: "collection"
    - name: "num_splits"
      type: "number"
    properties:
    - name: "resource"
      value: "arn:aws:lambda:us-east-2:735406098573:function:ir-split"
- parallelFor:
    name: "ParallelFor"
    dataIns:
    - name: "images_s3_keys"
      type: "collection"
      source: "ir-split/batches"
      constraints:
      - name: "distribution"
        value: "BLOCK(1)"
    - name: "s3bucket"
      type: "string"
      source: "IMGREC/s3bucket"
      constraints:
      - name: "distribution"
        value: "REPLICATE(*)"
    - name: "topic_arn"
      type: "string"
      source: "IMGREC/topic_arn"
      constraints:
      - name: "distribution"
        value: "REPLICATE(*)"
    loopCounter:
      type: "number"
      to: "ir-split/num_splits"
      step: "1"
    loopBody:
    - function:
        name: "preprocess-imgs"
        type: "String"
        dataIns:
        - name: "images_s3_keys"
          type: "collection"
          source: "ParallelFor/images_s3_keys"
        - name: "s3bucket"
          type: "string"
          source: "ParallelFor/s3bucket"
        - name: "topic_arn"
          type: "string"
          source: "ParallelFor/topic_arn"
        dataOuts:
        - name: "cropped_images_s3_keys"
          type: "collection"
        - name: "cropped_images_timestamps"
          type: "collection"
        - name: "topic_arn"
          type: "string"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:735406098573:function:preprocess-imgs"
    - function:
        name: "ir-delta"
        type: "String"
        dataIns:
        - name: "cropped_images_s3_keys"
          type: "collection"
          source: "preprocess-imgs/cropped_images_s3_keys"
        - name: "cropped_images_timestamps"
          type: "collection"
          source: "preprocess-imgs/cropped_images_timestamps"
        - name: "s3bucket"
          type: "string"
          source: "preprocess-imgs/s3bucket"
        - name: "topic_arn"
          type: "string"
          source: "preprocess-imgs/topic_arn"
        dataOuts:
        - name: "all_passed"
          type: "bool"
        - name: "invalid_units_frame_keys"
          type: "collection"
        - name: "invalid_units_timestamps"
          type: "collection"
        - name: "ingested_frame_keys"
          type: "collection"
        - name: "ingested_frame_timestamps"
          type: "collection"
        - name: "topic_arn"
          type: "string"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:735406098573:function:ir-delta"
    - function:
        name: "log-valid"
        type: "String"
        dataIns:
        - name: "ingested_frame_keys"
          type: "collection"
          source: "ir-delta/ingested_frame_keys"
        - name: "ingested_frame_timestamps"
          type: "collection"
          source: "ir-delta/ingested_frame_timestamps"
        - name: "topic_arn"
          type: "string"
          source: "ir-delta/topic_arn"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:735406098573:function:ir-log-valid"
    dataOuts:
    - name: "invalid_units_frame_keys_batches"
      type: "collection"
      source: "ir-delta/invalid_units_frame_keys"
    - name: "invalid_units_frame_timestamps_batches"
      type: "collection"
      source: "ir-delta/invalid_units_timestamps"
    - name: "ingested_frame_keys_batches"
      type: "collection"
      source: "ir-delta/ingested_frame_keys"
    - name: "ingested_frame_timestamps_batches"
      type: "collection"
      source: "ir-delta/ingested_frame_timestamps"
- function:
    name: "ir-reduce"
    type: "String"
    dataIns:
    - name: "invalid_units_frame_keys_batches"
      type: "collection"
      source: "ParallelFor/invalid_units_frame_keys_batches"
    - name: "invalid_units_frame_timestamps_batches"
      type: "collection"
      source: "ParallelFor/invalid_units_frame_timestamps_batches"
    - name: "ingested_frame_keys_batches"
      type: "collection"
      source: "ParallelFor/ingested_frame_keys_batches"
    - name: "ingested_frame_timestamps_batches"
      type: "collection"
      source: "ParallelFor/ingested_frame_timestamps_batches"
    dataOuts:
    - name: "average_deviation"
      type: "number"
    properties:
    - name: "resource"
      value: "arn:aws:lambda:us-east-2:735406098573:function:ir-reduce"
- if:
    name: "IfThenElse1"
    dataIns:
    - name: "average_deviation"
      type: "number"
      source: "ir-reduce/average_deviation"
    - name: "invalid_units_frame_keys_batches"
      type: "collection"
      source: "ParallelFor/invalid_units_frame_keys_batches"
    - name: "invalid_units_frame_timestamps_batches"
      type: "collection"
      source: "ParallelFor/invalid_units_frame_timestamps_batches"
    condition:
      combinedWith: "and"
      conditions:
      - data1: "IfThenElse1/average_deviation"
        data2: "0"
        operator: "<"
    then:
    - function:
        name: "log-valid-batch"
        type: "String"
        dataIns:
        - name: "average_deviation"
          type: "collection"
          source: "IfThenElse1/average_deviation"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:735406098573:function:ir-log-batch-valid"
    else:
    - function:
        name: "log-invalid-batch"
        type: "String"
        dataIns:
        - name: "average_deviation"
          type: "number"
          source: "IfThenElse1/average_deviation"
        - name: "invalid_units_frame_keys_batches"
          type: "collection"
          source: "IfThenElse1/invalid_units_frame_keys_batches"
        - name: "invalid_units_frame_timestamps_batches"
          type: "collection"
          source: "IfThenElse1/invalid_units_frame_timestamps_batches"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:us-east-2:735406098573:function:ir-log-batch-invalid"
dataOuts:
- name: "average_deviation"
  type: "number"
  source: "ir-reduce/average_deviation"
