---
name: "IMGREC"
workflowBody:
- function:
    name: "ir-split"
    type: "String"
- parallelFor:
    name: "ParallelFor"
    loopCounter: {}
    loopBody:
    - function:
        name: "preprocess-imgs"
        type: "String"
    - function:
        name: "ir-delta"
        type: "String"
    - if:
        name: "IfThenElse"
        condition: {}
        then:
        - function:
            name: "log-valid"
            type: "String"
        else:
        - function:
            name: "ir-convolute-reduce"
            type: "String"
        - function:
            name: "log-invalid"
            type: "String"
- function:
    name: "ir-reduce"
    type: "String"
- if:
    name: "IfThenElse1"
    condition: {}
    then:
    - function:
        name: "log-valid-batch"
        type: "String"
    else:
    - function:
        name: "log-invalid-batch"
        type: "String"
